name: Build, publish and release a Docker image

on:
  push:
    tags:
      - '*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag name
        shell: bash
        run: echo "TAG_NAME=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_ENV

      - name: Build and push Docker image latest
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Push Docker image Tag
        run: |
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG_NAME }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG_NAME }}
        if: github.event_name == 'push'

  rancher-upgrade:

    needs: build-and-push-image
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [gx-streamlit]

    steps:
      - name: upgrade ${{ matrix.service }}
        uses: sekassel-research/actions-rancher-update@v1.2.0
        with:
          rancher_url: https://rancher.dev.economia.gov.br
          rancher_access: ${{ secrets.RANCHER_ACCESS }}
          rancher_key: ${{ secrets.RANCHER_KEY }}
          project_id: 1a656207
          stack_name: gx-streamlit
          service_name: ${{ matrix.service }}
          docker_image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          retry_count: 20
          retry_delay: 15
